os: linux
dist: xenial  # first Travis Ubuntu distro to support Python 3.7
language: python
python:
- '3.6'
- '3.7'
addons:
  apt:
    packages:
    - foma-bin

before_install:
- pip install poetry
install:
- poetry install -vv
script:
- mypy fsttest
- pytest

env:
  global:
    secure: oVM+8WlICvktm8unjMoI4YxgSv5Zuq27aeLe9SvatMlZXmdTURyVvtLVK8DobEF1r52cxyuIRM4nW4k9Txq1kpYByjLKWSolROxBgZFvGodJYKAVOqlGhD57iNriCBx+APfuWXHtd0u5DLCd8WmqvNUzLKEmUDo75lzM7zN0mYTMVOh34/a49+Bmr96ktj/9YtnHWg1/4Ww7UKz3DvdkhxwUBMx/ysY7W0n7/NyzB63TwEHQGHaQfXhn3ENLGqcvx06/v7vTocHv/BQQ6VyzArx1/nDQviccPQlgtfww996mIWchSQkr6+k9wt+tO1vnVF5d2mAI7AwLZtKuHSp+FjC1DzKN6wtxIME8Vv53LX+nv4Yn6GN7vCleVxWzwvHYCr3a5t618wSu0Yj0E8sfodIFKS2CocpYkoCO2rItS1hUXfiDIq7Q2RWFciqx9NoCDxe/Oh1u/l9Jks8JQ13J7NPt3ChKPWycvvAPLaTCwqRilK1+9rPm2Nx+/j5+mqmfcZtDnJ9k/Hbi0x7I4Own6dYyzh6L4otlNDk3BwbFFkXIzzZ6R2smYkgWT/PUDNfdF5cdPL8KZsTR+EEdBdwbYJIPeai6m2Nv2tc0o7cDw02gDu1WgOxHRr2wK9gq9hu/4u2sQnQ8l2Dj2JUaawGfW/MwWcNnx2AO//cnKjbSc5w=

deploy:
  provider: script
  script: poetry publish --build --username=__token__ --password="$PYPI_API_KEY"
  on:
    tags: true
    python: '3.6'
