os: linux
dist: xenial  # first Travis Ubuntu distro to support Python 3.7
language: python
python:
- '3.6'
- '3.7'
addons:
  apt:
    packages:
    - foma-bin

before_install:
- pip install poetry
install:
- poetry install -vv
script:
- poetry run pytest
